### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by amanuel1995** [amanuel1995/MI-449-SS17-741-js-collect-and-display-information-kPt9Fl#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://amanuel1995.github.io/MI-449-SS17-741-js-collect-and-display-information-kPt9Fl/) and meets the following criteria:

- [x] Use [this base HTML](https://gist.github.com/chrisvfritz/1b25d9037fb64e3486ea2df8179f9ce8) (feel free to change it) to build a simple app that generates the HTML for a dating profile [in this format](https://gist.github.com/chrisvfritz/4043b4d043610a2bb9cd26444c3e7a45), using information collected from the user
- [x] Show a preview of the dating profile with rendered HTML (e.g. `<em>hella charming</em>` should appear as _hella charming_)
- [x] Also show the raw, generated HTML inside the `<pre><code></code></pre>` elements (e.g. `<em>hella charming</em>` should appear as `<em>hella charming</em>`)
- [x] Both the preview and raw HTML should update live as the user enters their information
- [x] All JavaScript is in a separate `.js` file
- [x] There are no linting errors in your JavaScript (this will also be expected for all future projects)

**Comment by KatieMFritz** [comment]
Hi Amanuel! 🌴 ⛄️ 

The app itself works _almost_ perfectly! 🌟 The thing that doesn't work yet is the contact links. The email link just sends an email to "email" and the phone link just tries to call "phone." Try googling "mailto syntax html" and "tel syntax html" if you can't figure it out.

There's some room for improvement in your JavaScript. You did a very nice job with naming your variables and with spacing/indentation - it's easy to read and understand your file! 👍 However, there is a lot of repeated code. For example, I see `'<h3>Hi, my name is ' + firstName` 8 times in the file. 😮 There are ways to structure this project where you'll only use that part once! Look again at the [refactoring code page of the lesson](https://msu.lansing.codes/courses/MI-449-SS17-741/lessons/js-collect-and-display-information/6) and see if you can find ways to use less code. If you'd like some real-time help, Erik and I are both available on Slack this afternoon and would be happy to do a screen-sharing or chat session. 😁

**Comment by amanuel1995** [comment]
All done!

**Comment by KatieMFritz** [comment]
☎️ and ✉️ links are working now! 🎉 

### Descriptive function names
The refactored JS is so much cleaner and shorter! 💥 🌟 However, I noticed you named your main function `updateRefactor`. A good rule for naming functions is to describe _what the function does_ (or for variables/values, _what it is_), not the process you went through to code it. That process belongs in your git commit messages (yours are awesome, by the way! :fire:). For this function, you could just call it `update`, `updateProfile`, or `updateText`. Does that make sense?

You also have a comment that describes what you changed, not what the function actually does. Save those changes for your git commit messages and use your code comments to describe the code as it is right now. 👍 

### Reduce duplicate code with variables
I notice that you're still duplicating a pretty long, complicated string: 
```js
'<h3>Hi, my name is ' + firstName + ' ' + lastName + '</h3>' + '\n' + '<p>' + bio + '</p>' + '\n' + '<p>' + 'If you\'re interested in a date, you can email me at ' + '<a href="mailto:' + email + '" target="_blank">' + email + '</a>' + ' or give me a call at <a href="tel:' + phone + '" target="_blank">' + phone + '</a>' + '</p>'
```
It's currently on [line 17](https://github.com/amanuel1995/MI-449-SS17-741-js-collect-and-display-information-kPt9Fl/blob/master/script.js#L17) and [line 19](https://github.com/amanuel1995/MI-449-SS17-741-js-collect-and-display-information-kPt9Fl/blob/master/script.js#L19). This would be a great place to use a variable! It's even worth making it a variable now, after you've already created it twice. That way, if you want to make any changes in the future, you only have to make them one time and you reduce the opportunity for bugs. 🐛 🐞 😄 

### Break long JavaScript statements into multiple lines

That same long line would also be easier to read if you broke it into multiple lines.

Check out _Spreading statements over mulitple lines_ on [page 6 of the "Use JS to collect, remember, and display info" lesson](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/js-collect-and-display-information/6) for an example.

> :bulb: **Some tips for doing this:**
> 
> * Choose your break points. Look for natural breaks in the statement, like commas or concatenation breaks. The lines don't have to be even. 
> * You can't just use `enter` to break up a string, but you can separate it with concatenation (`part 1` + `part 2`)
> * Be careful with indentation. Every line after the first should be indented _exactly one level_ to show that it's all part of the same statement. The exception is if it's a block of HTML - then you start with just one level of indentation, but you can indent further just like you would in an HTML file.
> * If the statement is "something = something else", and you're breaking "something else" into multiple lines, START "something else" on a new line (see the example). 

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by amanuel1995** [comment]
I am all done now! (Or I think so lol )

**Comment by KatieMFritz** [comment]
So much better! 🔥 🎉 🌟 💥 Very nice work making your code more concise. 

I have oooone more round of changes for you, so this code can be part of your portfolio. 

### Indentation
```js
  // create a string variable to hold value to be updated
  var profileString = '<h3>Hi, my name is ' + firstName + ' ' +
  lastName + '</h3>' + '\n' + '<p>' + bio + '</p>' + '\n' + '<p>' +
  'If you\'re interested in a date, you can email me at ' +
  '<a href="mailto:' + email + '" target="_blank">' + email +
  '</a>' + ' or give me a call at <a href="tel:' + phone +
  '" target="_blank">' + phone + '</a>' + '</p>'
```

This wonderful variable should be indented after the first line, to show that it's all one variable: 

```js
  // create a string variable to hold value to be updated
  var profileString = '<h3>Hi, my name is ' + firstName + ' ' +
    lastName + '</h3>' + '\n' + '<p>' + bio + '</p>' + '\n' + '<p>' +
    'If you\'re interested in a date, you can email me at ' +
    // and so on...
```
* * * 

### Line spacing (line breaks)

As you know, spacing is subjective - you can do whatever you want, as long as it's consistent. In this file, you only use line breaks twice, inside your `updateProfile` function. It makes it seem like those two lines (after the line breaks) are separate from the rest of the code, and that the rest of the code is all one idea. 

But really, you have several ideas going on in this file:

1. get elements by ID and assign [them] to variables
2. function to refactor code to update live-code/preview
3. get the `value`s of `input`s and assign them to variables
4. generate the dating profile itself
5. display the dating profile in two places on the page
6. trigger the update function whenever the user types something

I would use line breaks to separate each of those ideas, or at the very least, 1, 2, and 6 (the function could all be one big block).

What do you think? ❔ 

* * *
### Comments

While you're updating the spacing, check out your comments. I really like how you are using comments to introduce the major parts of your code - it makes it easier for me to understand what's going on, and it also helps you because you have to think about what the code is doing and explicitly describe it. 👍 ✨ 

Make sure your comments describe _what the code does now_, not _how it's changed_. For example, you'll almost never want to say "refactor" in a code comment. That belongs in a git commit message. 

Ideally, I should be able to read _only the comments_ and know exactly what the code _does_ (but maybe not _how_ it does it). Many developers even start by writing comments before they write their code! 💡 

* * *
### Optional: HTML ID syntax

Most of your HTML `id`s are using kebab-case ([name disputed](http://stackoverflow.com/questions/11273282/whats-the-name-for-hyphen-separated-case/12273101) but I mean lowercase-words-separated-by-hyphens), which is the standard. However, you are using `FirstName` and `LastName` as HTML `id`s. To make your code more consistent, you could change those to `first-name` and `last-name`. It's okay if you don't, though. 😸 

* * *
Please don't be discouraged about this latest round! Like I said, it's finishing touches so this code can be a reference for future you, or a part of your portfolio. You've done a great job refactoring it and making a very clean and functional app. 😄 

Let me know when you've made updates, or if you have questions! ✈️

**Comment by amanuel1995** [comment]
Thank you @KatieMFritz! You are amazing! You point out everything and also convince me why I should do so. 

I did the indentation, added few line breaks where I thought would make sense to do so. I have also tweaked and added few more code comments, increased consistency in HTML id names. Let me know if there's more or if I forgot something else. Otherwise, I think I've mastered this. 😄

**Comment by KatieMFritz** [comment]
![beautiful](https://cloud.githubusercontent.com/assets/7085184/23680322/d21c6ad0-0358-11e7-84b3-37c33103cd27.jpg)

:shipit:

**Comment by amanuel1995** [comment]
Awe thank you!
